### PR TITLE
Bug 1837867: Pass a single role for the spec'd admin user

### PR DESCRIPTION
**Pull request by jcantrill**
This pr:

* removes all roles except the admin role if so configured

https://bugzilla.redhat.com/show_bug.cgi?id=1837867

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill can you walk through why we need to make changes in the proxy at all for that bz?
from what I've noticed the opendistro multitenancy plugin will resolve your role based on
1) what roles you match
2) what operation you are trying to perform

**Comment by jcantrill** [comment]
> @jcantrill can you walk through why we need to make changes in the proxy at all for that bz?
> from what I've noticed the opendistro multitenancy plugin will resolve your role based on
> 
> 1. what roles you match
> 2. what operation you are trying to perform
Ref: https://docs.search-guard.com/latest/mapping-users-roles specifically the statement:

`A request can be assigned to one or more Search Guard roles. If a request is mapped to more than one role, the permissions of these roles are combined`

We are using proxy auth and sending the allowed roles via a header.  Additionally we have one role `project_user` which applies to every user.  By removing the `dls` for `admin_user` to allow access to all indices with no restriction we are still seeing OD filtering out records that are confirmed to be there when using the admin certs.  I believe what is happening is since the user is being matched to to both roles for the same index, OD merges the permission sets.  This means you are getting "*" + "dls" which = "dls"

**Pull request merged**
