### PR TITLE
LOG-967: Add prometheus metrics endpoint

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR enables prometheus metrics for the elasticsearch-proxy internal go runtime based on [prometheus/client_golang](github.com/prometheus/client_golang). This enables deeper introspection of memory/process usage besides cadvisor metrics.
 
/cc @blockloop 
/assign @ewolinetz
 
### Links
- Depending on PR(s): openshift/elasticsearch-operator#542

### CODE REVIEW

**Review by blockloop — CHANGES_REQUESTED** [review]
You're going to need to add https://godoc.org/github.com/dnesting/client_golang/prometheus#InstrumentHandler this to the proxy server so we can see HTTP metrics.

line 141 of server.go needs to be something like 

```go
proxy := NewWebSocketOrRestReverseProxy(u, opts)
serveMux.Handle(path, prometheus.InstrumentHandler("proxy", proxy))
```

**Comment by periklis** [comment]
> You're going to need to add https://godoc.org/github.com/dnesting/client_golang/prometheus#InstrumentHandler this to the proxy server so we can see HTTP metrics.
> 
> line 141 of server.go needs to be something like
> 
> ```go
> proxy := NewWebSocketOrRestReverseProxy(u, opts)
> serveMux.Handle(path, prometheus.InstrumentHandler("proxy", proxy))
> ```

After some research, the approach you are recommending is not supported by `prometheus/client_golang` anymore OOTB, because the all-or-nothing `InstrumentHandler` methods used to have various issues, e.g. used summaries instead of histograms. 

To implement http metrics based on `prometheus/client_golang` one needs to compose the primitives handlers on his/her own, e.g.: https://github.com/thanos-io/thanos/blob/master/pkg/extprom/http/instrument_server.go

As per this PR's intention was to introduces the go & process collector metrics only, do we need to replicate the http metrics which we already get from elasticsearch IIRC on the proxy side, too? WDYT?

**Comment by blockloop** [comment]
> > You're going to need to add https://godoc.org/github.com/dnesting/client_golang/prometheus#InstrumentHandler this to the proxy server so we can see HTTP metrics.
> > line 141 of server.go needs to be something like
> > ```go
> > proxy := NewWebSocketOrRestReverseProxy(u, opts)
> > serveMux.Handle(path, prometheus.InstrumentHandler("proxy", proxy))
> > ```
> 
> After some research, the approach you are recommending is not supported by `prometheus/client_golang` anymore OOTB, because the all-or-nothing `InstrumentHandler` methods used to have various issues, e.g. used summaries instead of histograms.
> 
> To implement http metrics based on `prometheus/client_golang` one needs to compose the primitives handlers on his/her own, e.g.: https://github.com/thanos-io/thanos/blob/master/pkg/extprom/http/instrument_server.go
> 
> As per this PR's intention was to introduces the go & process collector metrics only, do we need to replicate the http metrics which we already get from elasticsearch IIRC on the proxy side, too? WDYT?

Yes, you're right. I forgot that was outdated. But yes, I do think we should instrument our handler because we want to know latency, status codes, etc all from the proxy's point of view. Because we have custom middleware in the proxy we should monitor it separately. We also want to add a metric to measure the latency between proxy and ES as well.

**Comment by periklis** [comment]
> > > You're going to need to add https://godoc.org/github.com/dnesting/client_golang/prometheus#InstrumentHandler this to the proxy server so we can see HTTP metrics.
> > > line 141 of server.go needs to be something like
> > > ```go
> > > proxy := NewWebSocketOrRestReverseProxy(u, opts)
> > > serveMux.Handle(path, prometheus.InstrumentHandler("proxy", proxy))
> > > ```
> > 
> > 
> > After some research, the approach you are recommending is not supported by `prometheus/client_golang` anymore OOTB, because the all-or-nothing `InstrumentHandler` methods used to have various issues, e.g. used summaries instead of histograms.
> > To implement http metrics based on `prometheus/client_golang` one needs to compose the primitives handlers on his/her own, e.g.: https://github.com/thanos-io/thanos/blob/master/pkg/extprom/http/instrument_server.go
> > As per this PR's intention was to introduces the go & process collector metrics only, do we need to replicate the http metrics which we already get from elasticsearch IIRC on the proxy side, too? WDYT?
> 
> Yes, you're right. I forgot that was outdated. But yes, I do think we should instrument our handler because we want to know latency, status codes, etc all from the proxy's point of view. Because we have custom middleware in the proxy we should monitor it separately. We also want to add a metric to measure the latency between proxy and ES as well.

Here we go, I've added for the start:
- request duration
- total requests
- request size
- response size

WDYT? Missing any other metric?

**Review by blockloop — APPROVED** [review]
/lgtm love it

**Comment by periklis** [comment]
@blockloop May I have another :LGTM: label. This PR had to be rebased because of `go.mod` conflicts.

**Pull request merged**
