### PR TITLE
Bump k8s deps to v0.19.2

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR updates the 2y-old unsupported k8s dependencies to release-4.7 and in turn k8s v1.19.2.

/cc @blockloop
/assign @ewolinetz 

### Links

- Request: https://coreos.slack.com/archives/CB3HXM2QK/p1604912470337800
- JIRA: https://issues.redhat.com/browse/LOG-978

### CODE REVIEW

**Comment by stlaz** [comment]
0.19.3 is the current latest version
you may want to keep bump and non-automatic changes separately to simplify maintenance of the code

**Review by blockloop — APPROVED** [review]

**Pull request merged**
