### PR TITLE
Bug 1886856: Fix keep-alive configuration

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR addresses a set of configuration options to have a proper end-to-end keep-alive behavior from Fluentd to proxy to Elasticsearch.
 
/cc @blockloop 
/assign @ewolinetz 

#### Before
pr-57-before

#### After
pr-57-after

### Links:
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1886856
- Depending PRs: openshift/origin-aggregated-logging#2005, openshift/cluster-logging-operator#749

### CODE REVIEW

**Review by blockloop — APPROVED** [review]
/lgtm

**Comment by ewolinetz** [comment]
/hold
depends on https://github.com/openshift/cluster-logging-operator/pull/749

**Pull request merged**
