### PR TITLE
Sanity fixes

### PR DESCRIPTION
**Pull request by stlaz**
### Description
These are some sanity fixes that should serve either as preventive security measures, or simplify future development.

/cc @jcantrill @ewolinetz @lukas-vlcek 
/assign @jcantrill 

cherry-pick
* leaving this one up to you

### Links
none

### CODE REVIEW

**Comment by jcantrill** [comment]
@stlaz please squash the commits

**Comment by jcantrill** [comment]
@stlaz does this resolve https://bugzilla.redhat.com/show_bug.cgi?id=1895581 where user's assigned to a group who have project visibility but not directly to the project are unable to see project logs?

**Comment by stlaz** [comment]
> does this resolve https://bugzilla.redhat.com/show_bug.cgi?id=1895581 where user's assigned to a group who have project visibility but not directly to the project are unable to see project logs?

no, these are sanity fixes only, you need to check what broke in between 4.4 and 4.5

**Comment by stlaz** [comment]
what exactly do you want me to squash? Those commits seem valid separate logical blocks. Maybe the cosmetic change?

**Comment by stlaz** [comment]
@jcantrill I rebased the changes on top of the current master, nothing should've changed except for adding a context to the projectclient List call. PTAL.

**Pull request merged**
